/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ghtjr.projection.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PostCompensationEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6512965315807181688L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PostCompensationEvent\",\"namespace\":\"com.ghtjr.projection.avro\",\"fields\":[{\"name\":\"postId\",\"type\":\"string\"},{\"name\":\"reason\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PostCompensationEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PostCompensationEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PostCompensationEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PostCompensationEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PostCompensationEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PostCompensationEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PostCompensationEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PostCompensationEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PostCompensationEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence postId;
  private java.lang.CharSequence reason;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PostCompensationEvent() {}

  /**
   * All-args constructor.
   * @param postId The new value for postId
   * @param reason The new value for reason
   */
  public PostCompensationEvent(java.lang.CharSequence postId, java.lang.CharSequence reason) {
    this.postId = postId;
    this.reason = reason;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return postId;
    case 1: return reason;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: postId = (java.lang.CharSequence)value$; break;
    case 1: reason = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'postId' field.
   * @return The value of the 'postId' field.
   */
  public java.lang.CharSequence getPostId() {
    return postId;
  }


  /**
   * Sets the value of the 'postId' field.
   * @param value the value to set.
   */
  public void setPostId(java.lang.CharSequence value) {
    this.postId = value;
  }

  /**
   * Gets the value of the 'reason' field.
   * @return The value of the 'reason' field.
   */
  public java.lang.CharSequence getReason() {
    return reason;
  }


  /**
   * Sets the value of the 'reason' field.
   * @param value the value to set.
   */
  public void setReason(java.lang.CharSequence value) {
    this.reason = value;
  }

  /**
   * Creates a new PostCompensationEvent RecordBuilder.
   * @return A new PostCompensationEvent RecordBuilder
   */
  public static com.ghtjr.projection.avro.PostCompensationEvent.Builder newBuilder() {
    return new com.ghtjr.projection.avro.PostCompensationEvent.Builder();
  }

  /**
   * Creates a new PostCompensationEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PostCompensationEvent RecordBuilder
   */
  public static com.ghtjr.projection.avro.PostCompensationEvent.Builder newBuilder(com.ghtjr.projection.avro.PostCompensationEvent.Builder other) {
    if (other == null) {
      return new com.ghtjr.projection.avro.PostCompensationEvent.Builder();
    } else {
      return new com.ghtjr.projection.avro.PostCompensationEvent.Builder(other);
    }
  }

  /**
   * Creates a new PostCompensationEvent RecordBuilder by copying an existing PostCompensationEvent instance.
   * @param other The existing instance to copy.
   * @return A new PostCompensationEvent RecordBuilder
   */
  public static com.ghtjr.projection.avro.PostCompensationEvent.Builder newBuilder(com.ghtjr.projection.avro.PostCompensationEvent other) {
    if (other == null) {
      return new com.ghtjr.projection.avro.PostCompensationEvent.Builder();
    } else {
      return new com.ghtjr.projection.avro.PostCompensationEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for PostCompensationEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PostCompensationEvent>
    implements org.apache.avro.data.RecordBuilder<PostCompensationEvent> {

    private java.lang.CharSequence postId;
    private java.lang.CharSequence reason;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ghtjr.projection.avro.PostCompensationEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.postId)) {
        this.postId = data().deepCopy(fields()[0].schema(), other.postId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.reason)) {
        this.reason = data().deepCopy(fields()[1].schema(), other.reason);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing PostCompensationEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ghtjr.projection.avro.PostCompensationEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.postId)) {
        this.postId = data().deepCopy(fields()[0].schema(), other.postId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.reason)) {
        this.reason = data().deepCopy(fields()[1].schema(), other.reason);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'postId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPostId() {
      return postId;
    }


    /**
      * Sets the value of the 'postId' field.
      * @param value The value of 'postId'.
      * @return This builder.
      */
    public com.ghtjr.projection.avro.PostCompensationEvent.Builder setPostId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.postId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'postId' field has been set.
      * @return True if the 'postId' field has been set, false otherwise.
      */
    public boolean hasPostId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'postId' field.
      * @return This builder.
      */
    public com.ghtjr.projection.avro.PostCompensationEvent.Builder clearPostId() {
      postId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'reason' field.
      * @return The value.
      */
    public java.lang.CharSequence getReason() {
      return reason;
    }


    /**
      * Sets the value of the 'reason' field.
      * @param value The value of 'reason'.
      * @return This builder.
      */
    public com.ghtjr.projection.avro.PostCompensationEvent.Builder setReason(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.reason = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'reason' field has been set.
      * @return True if the 'reason' field has been set, false otherwise.
      */
    public boolean hasReason() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'reason' field.
      * @return This builder.
      */
    public com.ghtjr.projection.avro.PostCompensationEvent.Builder clearReason() {
      reason = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PostCompensationEvent build() {
      try {
        PostCompensationEvent record = new PostCompensationEvent();
        record.postId = fieldSetFlags()[0] ? this.postId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.reason = fieldSetFlags()[1] ? this.reason : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PostCompensationEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<PostCompensationEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PostCompensationEvent>
    READER$ = (org.apache.avro.io.DatumReader<PostCompensationEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.postId);

    out.writeString(this.reason);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.postId = in.readString(this.postId instanceof Utf8 ? (Utf8)this.postId : null);

      this.reason = in.readString(this.reason instanceof Utf8 ? (Utf8)this.reason : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.postId = in.readString(this.postId instanceof Utf8 ? (Utf8)this.postId : null);
          break;

        case 1:
          this.reason = in.readString(this.reason instanceof Utf8 ? (Utf8)this.reason : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










